// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/flight-search/flight-search-and-aggregation-system/internal/domain (interfaces: FlightProvider)
//
// Generated by this command:
//
//	mockgen -destination=provider_mock.go -package=domain github.com/flight-search/flight-search-and-aggregation-system/internal/domain FlightProvider
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFlightProvider is a mock of FlightProvider interface.
type MockFlightProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFlightProviderMockRecorder
	isgomock struct{}
}

// MockFlightProviderMockRecorder is the mock recorder for MockFlightProvider.
type MockFlightProviderMockRecorder struct {
	mock *MockFlightProvider
}

// NewMockFlightProvider creates a new mock instance.
func NewMockFlightProvider(ctrl *gomock.Controller) *MockFlightProvider {
	mock := &MockFlightProvider{ctrl: ctrl}
	mock.recorder = &MockFlightProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightProvider) EXPECT() *MockFlightProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockFlightProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFlightProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFlightProvider)(nil).Name))
}

// Search mocks base method.
func (m *MockFlightProvider) Search(ctx context.Context, criteria SearchCriteria) ([]Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, criteria)
	ret0, _ := ret[0].([]Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFlightProviderMockRecorder) Search(ctx, criteria any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFlightProvider)(nil).Search), ctx, criteria)
}
